---
# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: sort-simple-yaml
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: check-yaml
      - id: check-json
        files: ^tests/app/
      - id: pretty-format-json
        args: ["--no-sort-keys", "--autofix"]
        files: ^tests/app/

  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: tests

  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - --line-length=119

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        description: Security oriented static analyser for python code
        exclude: tests/|scripts/|lib/helpers
        args:
          - -s
          - B101,B311,B105

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.13
    hooks:
      - id: vulture
        description: Find dead Python code
        args:
          [
            "--min-confidence",
            "90",
            "--exclude",
            "tests,env,lib/schemas/fields.py",
            "--ignore-names",
            "einfo,task_id,retval,logger,log_method,exc,args",
            ".",
          ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell -L som
        language: python
        types: [text]
        additional_dependencies:
          - tomli

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path", "pyproject.toml", "."]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
        args: ["--disable", "line-length"]
